name: Reusable workflow - code checkout
runs:
  using: "composite"
  steps: 
    - name: Get Actions user id
      id: get_uid
      run: |
        actions_user_id=`id -u $USER`
        echo $actions_user_id
        echo ::set-output name=uid::$actions_user_id
    - name: Correct Ownership in GITHUB_WORKSPACE directory
      uses: peter-murray/reset-workspace-ownership-action@v1
      with:
        user_id: ${{ steps.get_uid.outputs.uid }}
    - name: code checkout
      uses: actions/checkout@v2
      #shell: bash