name: "Build docker image"
description: "Build docker image..."
inputs:
  image-name:
    description: "The image name to use"
    required: true
  image-version:
    description: "The image version to use"
    required: true
  dockerfile-path:
    description: "The path to dockerfile"
    required: true
    

runs:
  using: "composite"
  steps: 
    #- name: Setup dotnet
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: ${{ inputs.dotnet-version }}

    - name: Getting Image information
      run: |
        echo "image-name:"    ${{ inputs.image-name }}
        echo "image-version:" ${{ inputs.image-version }}
        echo "dockerfile-path:" ${{ inputs.dockerfile-path }}
      shell: bash

    - uses: actions/checkout@v2

    - name: Build docker image 
      run: docker build ${{ inputs.dockerfile-path }} ${{ inputs.image-name }}:${{ inputs.image-version }}
      shell: bash


